### ISSUE TITLE
how can we login as a teacher ?

### ISSUE THREAD

**Issue by menoc61** [abhidevs/webdesk#16]
I have analised and comple back the code restructure it and find out there was a problem from the login 
when login the user is recognizer directly as a student but there is no way of setting his state to isAdmin or isTeacher on the interface 
Even if you set it from the database... he will steal be  considered as a student @abhidevs  how can we fixed that?

**Comment by abhidevs** [comment]
@menoc61  By default, every user is considered as student, but you can set the user's `isTeacher` model field to `True` in the database, then the user will be converted to a Teacher.
